/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 4.6 */
/* Fri May 25 18:32:25 2018 */

/* parameterized module instance */
count32 __ (.Clock( ), .Clk_En( ), .Aclr( ), .Q( ));
